### ISSUE TITLE
Example please

### ISSUE THREAD

**Issue by Sergio-tix** [i8beef/node-red-contrib-animate-gif#6]
If it is not hard for you, please show an example, as from 3 images make GIF animation. 
I get an error "Error: No matching constructor overloading was found. Please see the docs for how to call the Jimp constructor."

**Comment by i8beef** [comment]
You need to make sure you are passing an array of `Buffer` in msg.payload. Whatever you are passing here, the underlying Jimp library doesn't like it. How are you sourcing the image Buffers?

**Comment by Sergio-tix** [comment]
I can get image Buffers from the image node (image, buffer, base64), I just wanted to test with the same frames, so I did this:
```
msg.payload = {
  delay: 500,
  dimensionX: 100,
  dimensionY: 100,
  quality: 60,
  repeat: true,
  payload: [msg.image, msg.image, msg.image]
}
return msg;
```
![4444](https://user-images.githubusercontent.com/18720428/114975308-b4bfa280-9e8c-11eb-87c0-e39c81ad2f37.PNG)

**Comment by i8beef** [comment]
Are you sure that should be `msg.image` and not `msg.payload`?

You can check to see what you are holding in that function with the following: `typeof msg.payload === 'object' && Buffer.isBuffer(msg.payload)`, if that doesn't return true, then thats why Jimp is complaining.

**Comment by Sergio-tix** [comment]
> Are you sure that should be `msg.image` and not `msg.payload`?

Yess. the image node passes the image to msg.image.

Thanks for trying to help. But I use Node-Red only for the reason that I am not a programmer.
Therefore, I did not begin to further understand the details of the work of gif node and made the conversion to GIF through ffmpeg.
